version: "3.8"
services:
  app:
    build: .
    command: ["npx", "vite", "--host", "0.0.0.0"]
    ports:
      - 5173:5173
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
